platform :ios, '9.0'
use_frameworks!

target 'SteamReader' do
pod 'Alamofire', '~> 3.3.1'
pod 'SwiftyJSON', '~> 2.3.2'
pod 'MagicalRecord', '~> 2.3.2'
pod 'SnapKit', '~> 0.20.0'
pod 'AsyncSwift', '~> 1.7.2'
#pod 'Spring', '~> 1.0.3'
end